[tool.poetry]
name = "pdf-scripts"
version = "0.0.0"
description = ""
authors = ["Johannes Filter <hi@jfilter.de>"]

[tool.poetry.dependencies]
python = "^3.10"
fasttext = "*"
pdftotext = "*"
tqdm = ">=4.66.3"
opencv-python = ">=4.8.1.78"

[tool.poetry.group.dev.dependencies]
black = ">=26.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
